### ISSUE TITLE
Multiple Dates Request

### ISSUE THREAD

**Issue by joaoftrodrigues** [joaoftrodrigues/RenExplore#1]
# Contextualization

So far, the date to search is a constant value. 
The aim of the project, is to retrieve tickets' information, for different dates, from different dates of access, for at least 1 trip.

# Tasks needed
Follow, it's exposed the tasks necessary to achieve 
- [ ]  Add new parameter to the function _run( )_ - which will receive the date to use on the request
- [ ] Generate the dates to use on each iteration - this is done outside the _run( )_ function
- [ ] Change the current value of date on request to the variable that will hold the date to use
